bot:
  name: ${BOT_NAME}
  token: ${TOKEN}

spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/ccc?authSource=admin
  jackson:
    mapper:
      accept-case-insensitive-enums: true